### PR TITLE
Validate reply from external API

### LINKED ISSUE #34: Sequence diagram in README is inaccurate
The PACS.002 response is not validated by the internal API as shown in the sequence diagram. This should either be removed from the sequence diagram or added to the internal API implementation.

### PR DESCRIPTION
**Pull request by william-stacken**
Make sure the response message from the external API is a valid pacs.002 message or return an error message.
Fixes #34

### CODE REVIEW

**Comment by william-stacken** [comment]
@Cactu5 please review. Note though that I chose 502 as the status when the response doesn't parse properly instead of 500 in the sequence diagram as I thought it was more appropriate. (There is no internal server error in the internal API, the problem is on the remote side)

**Comment by william-stacken** [comment]
Actually, I now realized I need to rethink this. The response doesn't necessarily need to be a pacs.002 message, it can simply be an XML error response.

**Comment by william-stacken** [comment]
Alright, should be all good now. I manually tested the new error message from the internal API and made sure that error responses from the external API didn't get flagged as bad responses in the internal API.

**Review by Cactu5 — APPROVED** [review]
👍

**Pull request merged**
